int main(void) {
	// Test cases generated by AI, it is better at generating random data than me.
	// Few test cases were tweaked by hand, though but it seems this covers most
	// of cases
	const char* i = "/usr/bin/";
	char* o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ("/usr/bin", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, "/usr/bin", o);
	i = "/usr//bin///env";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ("/usr/bin/env", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, "/usr/bin/env", o);
	i = "./src/././main.c";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ("src/main.c", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, "src/main.c", o);
	i = "src/../include/header.h";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ("include/header.h", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, "include/header.h", o);
	i = "../../etc/config";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ("../../etc/config", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, "../../etc/config", o);
	i = "/home/user/.././docs//file.txt";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ("/home/docs/file.txt", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, "/home/docs/file.txt", o);
	i = "///";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ("/", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, "/", o);
	i = "./././";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ(".", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, ".", o);
	i = "../a/./b/../../c/";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ("../c", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, "../c", o);
	i = "";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ(".", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, ".", o);
	i = "..";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ("..", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, "..", o);
	i = "C:/abc////d";
	o = cbuild_path_normalize(i);
	TEST_ASSERT_STREQ("C:/abc/d", o, "Wrong path after normalization of \"%s\""
		TEST_EXPECT_MSG(s), i, "C:/abc/d", o);
	return 0;
}
