CBuild: CBuild::ccj_out Class Reference
CBuild::ccj_out Class Reference
Generates compile_commands.json.
#include <ccj.hpp>
Public Member Functions
ccj_out ()
Create new compile_commands.json generator.
virtual void generate (CBuild::RType mode, lib::map< std::string, std::string > *args)
Generate some output.
virtual bool init ()
Some init.
Public Member Functions inherited from CBuild::generator_base
generator_base (std::string out)
Create and save output file name.
Additional Inherited Members
Protected Attributes inherited from CBuild::generator_base
std::string OUT
Detailed Description
Generates compile_commands.json.
Definition at line 37 of file ccj.hpp.
Constructor & Destructor Documentation
ccj_out()
CBuild::ccj_out::ccj_out () inline
Create new compile_commands.json generator.
Definition at line 42 of file ccj.hpp.
Member Function Documentation
generate()
void CBuild::ccj_out::generate (CBuild::RType mode, lib::map< std::string, std::string > * args) virtual
Generate some output.
Parameters
mode => CBuild::RType -> CBuild arg
args => lib::map<std::string, std::string> -> CBuild arg
Implements CBuild::generator_base.
Definition at line 190 of file generator.cpp.
References lib::map< _K, _D >::at(), CBuild::BUILD, CBuild::fs::create(), CBuild::line_filebuff::del_line(), CBuild::eval_cmd(), CBuild::fs::exists(), CBuild::fs::FILE, lib::map< _K, _D >::get(), CBuild::line_filebuff::get_line(), lib::map< _K, _D >::get_ptr(), CBuild::Registry::GetToolchain(), CBuild::MAGENTA, CBuild::preprocess_json_str(), CBuild::print(), CBuild::print_full(), lib::map< _K, _D >::push_back(), CBuild::RED, CBuild::line_filebuff::set_line(), lib::map< _K, _D >::size(), and CBuild::line_filebuff::update().
init()
bool CBuild::ccj_out::init () virtual
Some init.
Returns
bool -> Work as logger/capture execution thread (true/false)
Implements CBuild::generator_base.
Definition at line 326 of file generator.cpp.
References CBuild::disable_system().
The documentation for this class was generated from the following files:
CBuild/headers/generator/ccj.hpp
CBuild/CBuild/src/generator.cpp