CBuild: CBuild::CBuildDependency Class Reference
CBuild::CBuildDependency Class Reference
#include <cbuild_dep.hpp>
Public Member Functions
CBuildDependency (std::string path, std::string target_id, std::string headers_dir)
bool need_prepare () override
std::string cargs () override
std::string largs () override
void prepare () override
void compile (std::string str)
Protected Attributes
std::string path
std::string target_id
std::string headers_dir
Detailed Description
Definition at line 36 of file cbuild_dep.hpp.
Constructor & Destructor Documentation
CBuildDependency()
CBuild::CBuildDependency::CBuildDependency (std::string path, std::string target_id, std::string headers_dir) inline
Definition at line 43 of file cbuild_dep.hpp.
References headers_dir, path, and target_id.
Member Function Documentation
cargs()
std::string CBuild::CBuildDependency::cargs () inline override virtual
Implements CBuild::Dependency.
Definition at line 57 of file cbuild_dep.hpp.
References CBUILD_CACHE_DIR, and CBUILD_PROJECT_DEPS_HEADERS.
compile()
void CBuild::CBuildDependency::compile (std::string str) inline
Definition at line 131 of file cbuild_dep.hpp.
References CBuild::exit(), CBuild::print(), CBuild::RED, and CBuild::system().
Referenced by prepare().
largs()
std::string CBuild::CBuildDependency::largs () inline override virtual
Implements CBuild::Dependency.
Definition at line 61 of file cbuild_dep.hpp.
References CBUILD_BUILD_DIR, CBUILD_CACHE_DIR, CBUILD_METADATA_FILE_EXTENSION, CBUILD_PROJECT_DEPS_DIR, CBuild::target_metadata_file::out, and CBuild::read_target_metadata_direct().
need_prepare()
bool CBuild::CBuildDependency::need_prepare () inline override virtual
Implements CBuild::Dependency.
Definition at line 48 of file cbuild_dep.hpp.
References CBUILD_BUILD_DIR, CBUILD_CACHE_DIR, CBUILD_METADATA_FILE_EXTENSION, CBUILD_PROJECT_DEPS_DIR, CBuild::fs::exists(), CBuild::target_metadata_file::out, and CBuild::read_target_metadata_direct().
prepare()
void CBuild::CBuildDependency::prepare () inline override virtual
Implements CBuild::Dependency.
Definition at line 72 of file cbuild_dep.hpp.
References CBuild::target_metadata_file::cargs, CBUILD_BUILD_CACHE_DIR, CBUILD_BUILD_DIR, CBUILD_BUILD_OUT_DIR, CBUILD_CACHE_DIR, CBUILD_METADATA_FILE_EXTENSION, CBUILD_METADATA_FOLDER, CBUILD_PROJECT_DEPS_DIR, CBUILD_PROJECT_DEPS_HEADERS, compile(), CBuild::target_metadata_file::compiler, CBuild::fs::copy(), CBuild::fs::create(), CBuild::fs::DIR, CBuild::fs::dir(), CBuild::GREEN, CBuild::target_metadata_file::largs, CBuild::target_metadata_file::linker, CBuild::MAGENTA, CBuild::source_metadata_file::object, CBuild::target_metadata_file::out, CBuild::print(), CBuild::print_full(), CBuild::read_file_metadata_direct(), CBuild::read_target_metadata_direct(), CBuild::RED, and CBuild::source_metadata_file::source.
Member Data Documentation
headers_dir
std::string CBuild::CBuildDependency::headers_dir protected
Definition at line 40 of file cbuild_dep.hpp.
Referenced by CBuildDependency().
path
std::string CBuild::CBuildDependency::path protected
Definition at line 38 of file cbuild_dep.hpp.
Referenced by CBuildDependency().
target_id
std::string CBuild::CBuildDependency::target_id protected
Definition at line 39 of file cbuild_dep.hpp.
Referenced by CBuildDependency().
The documentation for this class was generated from the following file:
CBuild/headers/dependency/cbuild_dep.hpp