CBuild: CBuild::NetDependency Class Reference
CBuild::NetDependency Class Reference
#include <net_dep_helper.hpp>
Protected Member Functions
void git_fetch (std::string server, std::string repo)
void file_fetch (std::string url, std::string file, std::string args="")
Additional Inherited Members
Public Member Functions inherited from CBuild::Dependency
virtual bool need_prepare ()=0
virtual void prepare ()=0
virtual std::string cargs ()=0
virtual std::string largs ()=0
Detailed Description
Definition at line 34 of file net_dep_helper.hpp.
Member Function Documentation
file_fetch()
void CBuild::NetDependency::file_fetch (std::string url, std::string file, std::string args = "") inline protected
Definition at line 46 of file net_dep_helper.hpp.
References CBuild::system().
git_fetch()
void CBuild::NetDependency::git_fetch (std::string server, std::string repo) inline protected
Definition at line 36 of file net_dep_helper.hpp.
References CBUILD_CACHE_DIR, CBuild::fs::create(), CBuild::fs::DIR, CBuild::fs::remove(), and CBuild::system().
The documentation for this class was generated from the following file:
CBuild/headers/dependency/net_dep_helper.hpp