CBuild: CBuild/CBuild/src/gcc_hash.cpp File Reference
gcc_hash.cpp File Reference
GCC hash impementation's implemetation.
#include "../../headers/map.hpp"
#include "fstream"
#include "sstream"
#include "string"
#include "vector"
#include "../../headers/build_data.hpp"
#include "../../headers/filesystem++.hpp"
#include "../../headers/hasher/gcc_hash_impl.hpp"
#include "../../headers/print.hpp"
#include "../../headers/register.hpp"
#include "../../headers/system.hpp"
Classes
struct extended_metadata
Functions
bool check_mismatch_recursive (const extended_metadata *file, std::vector< extended_metadata > *source_metadata, lib::map< std::string, extended_metadata > *header_metadata)
Detailed Description
GCC hash impementation's implemetation.
Author
WolodiaM (w_mel.nosp@m.nyk@.nosp@m.outlo.nosp@m.ok.c.nosp@m.om)
Date
2024-01-06
Copyright
(C) 2024 WolodiaM @license GPL v3.0 or later
Copyright (C) 2024 WolodiaM This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.
Definition in file gcc_hash.cpp.
Function Documentation
check_mismatch_recursive()
bool check_mismatch_recursive (const extended_metadata * file, std::vector< extended_metadata > * source_metadata, lib::map< std::string, extended_metadata > * header_metadata)
Definition at line 41 of file gcc_hash.cpp.
References check_mismatch_recursive(), CBuild::source_metadata_file::deps, lib::map< _K, _D >::get(), CBuild::source_metadata_file::hash, extended_metadata::meta, CBuild::source_metadata_file::object, extended_metadata::old_meta, and extended_metadata::old_metadata_available.
Referenced by check_mismatch_recursive(), and CBuild::gcc_hash_impl().