CBuild: CBuild/CBuild/src/metadata_file.cpp File Reference
metadata_file.cpp File Reference
Implementation for build_data.hpp.
#include "cstdint"
#include "fstream"
#include "sstream"
#include "string"
#include "vector"
#include "../../headers/CBuild_defs.hpp"
#include "../../headers/build_data.hpp"
#include "../../headers/filesystem++.hpp"
#include "../../headers/print.hpp"
Functions
int read_file_metadata_internal (std::string path, CBuild::source_metadata_file *metadata)
Detailed Description
Implementation for build_data.hpp.
Author
WolodiaM (w_mel.nosp@m.nyk@.nosp@m.outlo.nosp@m.ok.c.nosp@m.om)
Date
2023-12-06
@license GPL v3.0 or later
Copyright (C) 2023 WolodiaM This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.
Definition in file metadata_file.cpp.
Function Documentation
read_file_metadata_internal()
int read_file_metadata_internal (std::string path, CBuild::source_metadata_file * metadata)
Definition at line 33 of file metadata_file.cpp.
References CBuild::source_metadata_file::deps, CBuild::fs::exists(), CBuild::source_metadata_file::hash, CBuild::source_metadata_file::object, and CBuild::source_metadata_file::source.
Referenced by CBuild::read_file_metadata(), and CBuild::read_file_metadata_direct().