CBuild: CBuild Namespace Reference
CBuild Namespace Reference
Filebuffer for CBuild ecosystem.
Namespaces
consts
Constants.
fs
Registry
types
vars
Classes
struct Path
Path datatype.
struct Project_dependency
Project dependency data.
class Toolchain
Toolchain class.
class GXX
class GCC
class MINGW_GXX
class MINGW_GCC
class filebuff
Base class of filebuffer.
class line_filebuff
class str_filebuff
class ccj_out
Generates compile_commands.json.
class generator_base
Base for any generator.
class makefile_out
Generate Makefile from task/target, works as command logger.
struct package_info
Package info struct for data for pkg-config.
class Help
class Task
Task, can be runned from shell or code.
struct cmd
Command for compile_commands.json.
class Init
Init task.
class Version
Version task.
class TaskList
class ToolchainList
class GeneratorList
class CmdList
Typedefs
typedef enum CBuild::ARG_TYPE ARG_TYPE
using handler = ARG_TYPE(*)(lib::map< std::string, std::string > *, char **, int, int, CBuild::RType *)
Handler for specific argument.
typedef struct CBuild::package_info package_info
Package info struct for data for pkg-config.
Enumerations
enum stage { PRE , POST }
Type of depencesies for toolchain.
enum build_type { EXECUTABLE , STATIC_LIBRARY , DYNAMIC_LIBRARY }
enum RType {
TASK , BUILD , RUN , BUILD_RUN ,
DEBUG , CLEAR , REBUILD , LOAD_DEPS ,
ERROR
}
Run mode.
enum ARG_TYPE {
BLANK_ARG = 0 , SIMPLE_ARG = 1 , TASK_ARG = 2 , TOOLCHAIN_ARG = 2 ,
GENERICK_ARG = 2 , GENERATOR_ARG = 2 , INC_ONE = 1 , INC_TWO = 2 ,
INC_THREE = 3 , INC_FOUR = 4 , INC_FIVE = 5 , INC_SIX = 6 ,
INC_SEVEN = 7 , INC_EIGHT = 8 , INC_NINE = 9 , INC_TEN = 10
}
Type of argument, indicate how many tokens this argument consumes, including self.
enum buffer_state { MATCH , FILE_NEWER , BUFFER_NEWER }
Represent atate of buffer.
enum color {
BLACK = 30 , RED = 31 , GREEN = 32 , YELLOW = 33 ,
BLUE = 34 , MAGENTA = 35 , CYAN = 36 , WHITE = 37
}
Text color.
Functions
RType parse (lib::map< std::string, std::string > *args, int argc, char **argv)
Parse arguments.
void loop (RType mode, lib::map< std::string, std::string > *args)
loop of CBuild
void rebuild (std::string scripts)
Rebuild userspace part of CBuild.
std::string get_version_string ()
Return version as string.
int get_version_major ()
Get major component of CBuild version.
int get_version_minor ()
Get minor component of CBuild version.
int * get_version_array ()
Get full CBuild version as int array of two components, no oveflow or rewrite check !
std::string get_random_string (unsigned int length)
Generate random string with specified range, on Linux can use /dev/urandom.
void exit (int code)
bool register_parse_handler (std::string cmd, CBuild::handler parser)
Register new handler for parsing cli args, see handler typedef comment to guide how to write handlers.
void add_env_var (std::string var, std::string value)
Add environment variable to CBuild::system and CBuild::system_piped calls.
std::string remove_env_var (std::string var)
Remove registered environment var.
void change_env_var (std::string var, std::string new_value)
Change value for environment var.
std::vector< std::string > parse_lines (std::string in)
Parse string to vector of strings.
std::vector< std::string > get_files (std::vector< std::string > files, std::string toolchain_id)
Get changed files.
void print_files ()
Print temporary file array.
bool get_pkg_info (CBuild::package_info *package)
Get the package info from pkg-config database.
void print (std::string msg, color fg=CBuild::WHITE)
Print colored text to STDOUT.
void print_full (std::string msg, color fg=CBuild::WHITE)
Print colored text to STDOUT if verbose flag is set.
void print_verbose ()
Enable verbose flag.
void print_none ()
Fully disable all print though CBuild::print.
int system (std::string cmd)
Call stdlib system() and print cmd to shell.
std::string system_piped (std::string cmd, unsigned int buffsize)
Execute command and return it's output.
std::vector< std::string > * get_log ()
Get the internall command log.
void disable_system ()
Disable system call to commands.
ARG_TYPE force_handler (lib::map< std::string, std::string > *args, char **argv __attribute_maybe_unused__, int argc __attribute_maybe_unused__, int ptr __attribute_maybe_unused__, CBuild::RType *type __attribute_maybe_unused__)
ARG_TYPE out_handler (lib::map< std::string, std::string > *args, char **argv, int argc __attribute_maybe_unused__, int ptr, CBuild::RType *type __attribute_maybe_unused__)
ARG_TYPE generator_handler (lib::map< std::string, std::string > *args, char **argv, int argc, int ptr, CBuild::RType *type __attribute_maybe_unused__)
ARG_TYPE build_handler (lib::map< std::string, std::string > *args, char **argv, int argc, int ptr, CBuild::RType *type)
ARG_TYPE task_handler (lib::map< std::string, std::string > *args, char **argv, int argc, int ptr, CBuild::RType *type)
ARG_TYPE arg_handler (lib::map< std::string, std::string > *args, char **argv, int argc, int ptr, CBuild::RType *type __attribute_maybe_unused__)
ARG_TYPE rebuild_handler (lib::map< std::string, std::string > *args __attribute_maybe_unused__, char **argv __attribute_maybe_unused__, int argc __attribute_maybe_unused__, int ptr __attribute_maybe_unused__, CBuild::RType *type)
std::string eval_cmd (std::array< std::string, 4 > data)
Evaluate compilation cmd.
std::string preprocess_json_str (std::string_view str)
Preprocess string for json.
CBuild::types::file_content get_file_data (std::string path, std::string included_from="")
Get content of file.
uint64_t hash (std::string str)
FNV-1a hashing function for std::string.
void procces_files (std::vector< std::string > files, std::string toolchain_id __attribute_maybe_unused__)
Procces file data.
void store_hash (std::string toolchain_id)
Store new hashes to file.
void load_hash (std::string toolchain_id)
Load old hashes.
void print_internal (std::string msg, CBuild::color fg)
std::string get_env_vars ()
Variables
int version [] = {CBUILD_VERSION_MAJOR, CBUILD_VERSION_MINOR}
bool real_exit = true
int arg = 0
int parg = 0
lib::map< std::string, handler > parsers_list
All handlers.
bool verbose = false
bool none = false
std::vector< std::string > log
std::map< std::string, std::string > env_vars
bool enabled = true
Detailed Description
Filebuffer for CBuild ecosystem.
Hasher v3.0 implementation.
Hasher v3.0 for CBuild.
Author
WolodiaM (w_mel.nosp@m.nyk@.nosp@m.outlo.nosp@m.ok.c.nosp@m.om)
Date
Wed May 3 01:44:19 PM EEST 2023
@license GPL v3.0 or later
Copyright (C) 2022 WolodiaM This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.
Author
WolodiaM (w_mel.nosp@m.nyk@.nosp@m.outlo.nosp@m.ok.c.nosp@m.om)
Date
Fri May 19 11:21:22 AM EEST 2023
@license GPL v3.0 or later
Copyright (C) 2022 WolodiaM This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.
Author
WolodiaM (w_mel.nosp@m.nyk@.nosp@m.outlo.nosp@m.ok.c.nosp@m.om)
Date
Fri May 19 11:32:50 AM EEST 2023
@license GPL v3.0 or later
Copyright (C) 2022 WolodiaM This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.
Typedef Documentation
ARG_TYPE
typedef enum CBuild::ARG_TYPE CBuild::ARG_TYPE
handler
using CBuild::handler = typedef ARG_TYPE (*)(lib::map<std::string, std::string> *, char **, int, int, CBuild::RType *)
Handler for specific argument.
Receives four arguments: lib::map<std::string, std::string> - arguments map char** - argv int - argc int - current parsing pointer, point to argument that call handler, default - 1 (self) CBuild::RType - type of run Returns int - consumed elements of argv
Definition at line 116 of file cli_parse_handler.hpp.
package_info
typedef struct CBuild::package_info CBuild::package_info
Package info struct for data for pkg-config.
Enumeration Type Documentation
ARG_TYPE
enum CBuild::ARG_TYPE
Type of argument, indicate how many tokens this argument consumes, including self.
Enumerator
BLANK_ARG
No argument.
SIMPLE_ARG
Only argument and no subarguments (like -f, -v)
TASK_ARG
Task argument (-t <task_id>)
TOOLCHAIN_ARG
Toolchain argument (-b/-r/-br/-c/-d <toolchain_id>)
GENERICK_ARG
Generick argument with subargument (-<arg> <subarg>
GENERATOR_ARG
Generator arg (-g <generator_id>)
INC_ONE
Increment by one, consumes only self.
INC_TWO
Increment by two, consumes self and 1 subarg.
INC_THREE
Increment by two, consumes self and 2 subarg.
INC_FOUR
Increment by two, consumes self and 3 subarg.
INC_FIVE
Increment by two, consumes self and 4 subarg.
INC_SIX
Increment by two, consumes self and 5 subarg.
INC_SEVEN
Increment by two, consumes self and 6 subarg.
INC_EIGHT
Increment by two, consumes self and 7 subarg.
INC_NINE
Increment by two, consumes self and 8 subarg.
INC_TEN
Increment by two, consumes self and 9 subarg.
Definition at line 37 of file cli_parse_handler.hpp.
buffer_state
enum CBuild::buffer_state
Represent atate of buffer.
Enumerator
MATCH
File match buffer.
FILE_NEWER
File is newer, buffer is not updated.
BUFFER_NEWER
Buffer is newer and file need update.
Definition at line 58 of file filebuff.hpp.
build_type
enum CBuild::build_type
Enumerator
EXECUTABLE
STATIC_LIBRARY
DYNAMIC_LIBRARY
Definition at line 52 of file Build.hpp.
color
enum CBuild::color
Text color.
Enumerator
BLACK
RED
GREEN
YELLOW
BLUE
MAGENTA
CYAN
WHITE
Definition at line 33 of file print.hpp.
RType
enum CBuild::RType
Run mode.
Enumerator
TASK
Run task.
BUILD
Build target.
RUN
Run target.
BUILD_RUN
Build and run target.
DEBUG
Build and run target in debug mode.
CLEAR
Clear build output and cache.
REBUILD
Rebuild user executable.
LOAD_DEPS
Load other project deps.
ERROR
Some error occurred.
Definition at line 33 of file CBuild.hpp.
stage
enum CBuild::stage
Type of depencesies for toolchain.
Enumerator
PRE
POST
Definition at line 51 of file Build.hpp.
Function Documentation
add_env_var()
void CBuild::add_env_var (std::string var, std::string value)
Add environment variable to CBuild::system and CBuild::system_piped calls.
Parameters
var => std::string -> Var name
value => std::string -> Var value
Definition at line 81 of file system.cpp.
References env_vars.
arg_handler()
ARG_TYPE CBuild::arg_handler (lib::map< std::string, std::string > * args, char ** argv, int argc, int ptr, CBuild::RType *type __attribute_maybe_unused__)
Definition at line 235 of file cli_parser.cpp.
References arg, exit(), GENERICK_ARG, GREEN, parg, print(), lib::map< _K, _D >::push_back_check(), and RED.
build_handler()
ARG_TYPE CBuild::build_handler (lib::map< std::string, std::string > * args, char ** argv, int argc, int ptr, CBuild::RType * type)
Definition at line 122 of file cli_parser.cpp.
References BUILD, BUILD_RUN, CLEAR, DEBUG, exit(), lib::map< _K, _D >::get_ptr(), CBuild::Registry::GetToolchainsList(), GREEN, LOAD_DEPS, print(), print_full(), lib::map< _K, _D >::push_back_check(), RED, RUN, and TOOLCHAIN_ARG.
change_env_var()
void CBuild::change_env_var (std::string var, std::string new_value)
Change value for environment var.
Parameters
var => std::string -> Var name
new_value => std::string -> New var value
Definition at line 89 of file system.cpp.
References env_vars.
disable_system()
void CBuild::disable_system ()
Disable system call to commands.
Definition at line 77 of file system.cpp.
References enabled.
Referenced by CBuild::ccj_out::init().
eval_cmd()
std::string CBuild::eval_cmd (std::array< std::string, 4 > data)
Evaluate compilation cmd.
Parameters
data => std::array<std::string, 4> -> Data:
0: File path
1: Object file
2: Compiler command
3: Args
Returns
std::string -> Command
Definition at line 113 of file generator.cpp.
Referenced by CBuild::ccj_out::generate().
exit()
void CBuild::exit (int code)
Definition at line 34 of file cli_parser.cpp.
References real_exit.
Referenced by arg_handler(), build_handler(), CBuild::Toolchain::crash(), generator_handler(), get_file_data(), loop(), out_handler(), parse(), and task_handler().
force_handler()
ARG_TYPE CBuild::force_handler (lib::map< std::string, std::string > * args, char **argv __attribute_maybe_unused__, int argc __attribute_maybe_unused__, int ptr __attribute_maybe_unused__, CBuild::RType *type __attribute_maybe_unused__)
Definition at line 39 of file cli_parser.cpp.
References print_full(), lib::map< _K, _D >::push_back_check(), RED, and SIMPLE_ARG.
generator_handler()
ARG_TYPE CBuild::generator_handler (lib::map< std::string, std::string > * args, char ** argv, int argc, int ptr, CBuild::RType *type __attribute_maybe_unused__)
Definition at line 82 of file cli_parser.cpp.
References exit(), GENERATOR_ARG, lib::map< _K, _D >::get_ptr(), CBuild::Registry::GetGeneratorsList(), GREEN, print(), print_full(), lib::map< _K, _D >::push_back_check(), and RED.
get_env_vars()
std::string CBuild::get_env_vars ()
Definition at line 35 of file system.cpp.
References env_vars.
Referenced by system(), and system_piped().
get_file_data()
CBuild::types::file_content CBuild::get_file_data (std::string path, std::string included_from = "")
Get content of file.
Parameters
path => std::string -> Path to file
included_from => std::string -> From what file included, for calculating path
Returns
std::string -> File content
Definition at line 143 of file hash.cpp.
References CBuild::fs::base(), CBuild::consts::c_multiline_comment(), CBuild::types::file_content::content, CBuild::consts::cxx_line_comment(), CBuild::consts::doxygen_comment(), exit(), CBuild::consts::include_parser(), CBuild::types::file_content::includes, CBuild::fs::normalize_path(), CBuild::types::file_content::path, print_full(), and RED.
Referenced by procces_files().
get_files()
std::vector< std::string > CBuild::get_files (std::vector< std::string > files, std::string toolchain_id)
Get changed files.
Parameters
files => std::vector<std::string> -> List of code files (.cpp/.c)
toolchain_id => std::string -> Id of toolchain, to get hash file
Definition at line 352 of file hash.cpp.
References CBuild::vars::filelist, CBuild::vars::headers, load_hash(), CBuild::vars::old_hashes, procces_files(), and store_hash().
Referenced by CBuild::Toolchain::gen_file_list().
get_log()
std::vector< std::string > * CBuild::get_log ()
Get the internall command log.
Returns
std::vector<std::string>* -> pointer to command log
Definition at line 74 of file system.cpp.
References log.
Referenced by CBuild::makefile_out::generate().
get_pkg_info()
bool CBuild::get_pkg_info (CBuild::package_info * package)
Get the package info from pkg-config database.
Parameters
package => package_info* -> Input and output from function
Returns
true -> All good
false -> Eroor, package not found
Definition at line 28 of file pkgconfig.cpp.
References CBuild::package_info::cargs, CBuild::Registry::largs, CBuild::package_info::largs, MAGENTA, CBuild::package_info::name, print(), RED, and system_piped().
Referenced by CBuild::Toolchain::call().
get_random_string()
std::string CBuild::get_random_string (unsigned int length)
Generate random string with specified range, on Linux can use /dev/urandom.
Parameters
length => usigned int -> String lenght
Returns
std::string -> Returned string
Definition at line 581 of file CBuild.cpp.
References MAGENTA, and print_full().
Referenced by CBuild::makefile_out::generate().
get_version_array()
int * CBuild::get_version_array ()
Get full CBuild version as int array of two components, no oveflow or rewrite check !
Returns
int* -> array of two parst of CBuild version
Definition at line 578 of file CBuild.cpp.
References version.
get_version_major()
int CBuild::get_version_major ()
Get major component of CBuild version.
Returns
int -> major version of CBuild
Definition at line 572 of file CBuild.cpp.
References CBUILD_VERSION_MAJOR.
get_version_minor()
int CBuild::get_version_minor ()
Get minor component of CBuild version.
Returns
int -> minor (patch) version of CBuild
Definition at line 575 of file CBuild.cpp.
References CBUILD_VERSION_MINOR.
get_version_string()
std::string CBuild::get_version_string ()
Return version as string.
Returns
std:;string -> version of CBuild
Definition at line 569 of file CBuild.cpp.
References CBUILD_VERSION_STR.
hash()
uint64_t CBuild::hash (std::string str)
FNV-1a hashing function for std::string.
Parameters
str => std::string -> Input string
Returns
uint64_t -> Hash of data
Definition at line 211 of file hash.cpp.
Referenced by procces_files().
load_hash()
void CBuild::load_hash (std::string toolchain_id)
Load old hashes.
Parameters
toolchain_id => std::string -> Id of toolchain
Definition at line 300 of file hash.cpp.
References CBUILD_BUILD_DIR, CBUILD_HASH_DIR, CBUILD_HASH_FILE, CBuild::fs::exists(), and CBuild::vars::old_hashes.
Referenced by get_files().
loop()
void CBuild::loop (CBuild::RType mode, lib::map< std::string, std::string > * args)
loop of CBuild
Parameters
mode => CBuild::RType -> from CBuild::parse function
args => lib::map<std::string, std::string>* -> args from CBuild::parse
Definition at line 284 of file CBuild.cpp.
References lib::map< _K, _D >::at(), BUILD, BUILD_RUN, CBuild::Toolchain::call(), CBuild::Registry::CallTask(), CBUILD_CACHE_DIR, CBUILD_COPY_CACHE_DIR, CBUILD_PROJECT_DEPS_DIR, CBUILD_PROJECT_DEPS_HEADERS, CBuild::Toolchain::clear(), CLEAR, CBuild::fs::create(), CBuild::Toolchain::debug(), DEBUG, CBuild::fs::DIR, ERROR, CBuild::fs::exists(), exit(), lib::map< _K, _D >::get(), lib::map< _K, _D >::get_ptr(), CBuild::Registry::GetGenerator(), CBuild::Registry::GetToolchain(), LOAD_DEPS, CBuild::Toolchain::load_project_deps(), print_none(), print_verbose(), CBuild::Toolchain::run(), RUN, lib::map< _K, _D >::size(), TASK, and CBuild::Registry::ToolchainAll().
out_handler()
ARG_TYPE CBuild::out_handler (lib::map< std::string, std::string > * args, char ** argv, int argc __attribute_maybe_unused__, int ptr, CBuild::RType *type __attribute_maybe_unused__)
Definition at line 52 of file cli_parser.cpp.
References exit(), lib::map< _K, _D >::get_ptr(), print(), print_full(), print_none(), print_verbose(), lib::map< _K, _D >::push_back_check(), RED, and SIMPLE_ARG.
parse()
CBuild::RType CBuild::parse (lib::map< std::string, std::string > * args, int argc, char ** argv)
Parse arguments.
Parameters
args => lib::map<std::string, std::string>* -> Returned arguments for other functions
argc => int -> argc from main
argv => char** -> argv from main
Returns
RType -> type of CBuild task
Definition at line 291 of file cli_parser.cpp.
References BLANK_ARG, ERROR, exit(), CBuild::Registry::GetKeywordsList(), CBuild::Registry::init(), CBuild::Registry::keywords, parsers_list, print(), lib::map< _K, _D >::push_back_check(), RED, SIMPLE_ARG, and TASK.
parse_lines()
std::vector<std::string> CBuild::parse_lines (std::string in) inline
Parse string to vector of strings.
Parameters
in => std::string -> Input string
Returns
std::vector<std::string> -> Returned list of lines
Definition at line 39 of file filebuff.hpp.
Referenced by CBuild::line_filebuff::set_str().
preprocess_json_str()
std::string CBuild::preprocess_json_str (std::string_view str)
Preprocess string for json.
Parameters
str => std::string_view -> Input string
Returns
std::string -> Output string
Definition at line 149 of file generator.cpp.
Referenced by CBuild::ccj_out::generate().
print()
void CBuild::print (std::string msg, color fg = CBuild::WHITE)
Print colored text to STDOUT.
Parameters
msg => std::string -> text to print
fg => CBuild::color -> color of text
Definition at line 49 of file print.cpp.
References none, and print_internal().
Referenced by arg_handler(), build_handler(), CBuild::Toolchain::call(), CBuild::Version::call(), CBuild::TaskList::call(), CBuild::ToolchainList::call(), CBuild::GeneratorList::call(), CBuild::CmdList::call(), CBuild::Help::call(), CBuild::Registry::CallTask(), CBuild::Toolchain::crash(), CBuild::Toolchain::debug(), CBuild::MINGW_GXX::debug(), CBuild::MINGW_GCC::debug(), CBuild::ccj_out::generate(), CBuild::makefile_out::generate(), generator_handler(), get_pkg_info(), out_handler(), parse(), CBuild::Toolchain::run(), CBuild::MINGW_GXX::run(), system(), system_piped(), and task_handler().
print_files()
void CBuild::print_files ()
Print temporary file array.
Definition at line 326 of file hash.cpp.
References CBuild::vars::filelist, MAGENTA, and print_full().
print_full()
void CBuild::print_full (std::string msg, color fg = CBuild::WHITE)
Print colored text to STDOUT if verbose flag is set.
Parameters
msg => std::string -> text to print
fg => CBuild::color -> color of text
Definition at line 54 of file print.cpp.
References none, print_internal(), and verbose.
Referenced by build_handler(), force_handler(), CBuild::Toolchain::gen_file_list(), CBuild::ccj_out::generate(), generator_handler(), get_file_data(), get_random_string(), out_handler(), print_files(), procces_files(), CBuild::Registry::RegisterGenerator(), CBuild::Registry::RegisterKeyword(), CBuild::Registry::RegisterTarget(), CBuild::Registry::RegisterTask(), and task_handler().
print_internal()
void CBuild::print_internal (std::string msg, CBuild::color fg)
Definition at line 28 of file print.cpp.
Referenced by print(), and print_full().
print_none()
void CBuild::print_none ()
Fully disable all print though CBuild::print.
Definition at line 62 of file print.cpp.
References none.
Referenced by loop(), and out_handler().
print_verbose()
void CBuild::print_verbose ()
Enable verbose flag.
Definition at line 59 of file print.cpp.
References verbose.
Referenced by loop(), and out_handler().
procces_files()
void CBuild::procces_files (std::vector< std::string > files, std::string toolchain_id __attribute_maybe_unused__)
Procces file data.
Parameters
files => std::vector<std::string> -> File list
toolchain_id => std::string -> used toolchain, for working with hash database
Definition at line 226 of file hash.cpp.
References CBuild::vars::filelist, get_file_data(), GREEN, hash(), CBuild::vars::headers, MAGENTA, CBuild::vars::old_hashes, print_full(), and RED.
Referenced by get_files().
rebuild()
void CBuild::rebuild (std::string scripts)
Rebuild userspace part of CBuild.
Parameters
scripts => std::string -> path to scripts dir
Definition at line 558 of file CBuild.cpp.
References CBuild::Registry::GetRebuildArgs(), and system().
rebuild_handler()
ARG_TYPE CBuild::rebuild_handler (lib::map< std::string, std::string > *args __attribute_maybe_unused__, char **argv __attribute_maybe_unused__, int argc __attribute_maybe_unused__, int ptr __attribute_maybe_unused__, CBuild::RType * type)
Definition at line 271 of file cli_parser.cpp.
References REBUILD, and SIMPLE_ARG.
register_parse_handler()
bool CBuild::register_parse_handler (std::string cmd, CBuild::handler parser)
Register new handler for parsing cli args, see handler typedef comment to guide how to write handlers.
Parameters
cmd => std::string -> Command that trigers this parser
parser => CBuild::handler -> Custom parsing function
Returns
bool -> true for success and false for failure
Definition at line 333 of file cli_parser.cpp.
References parsers_list.
remove_env_var()
std::string CBuild::remove_env_var (std::string var)
Remove registered environment var.
Parameters
var => std::string -> Var name
Returns
std::string -> Var value
Definition at line 84 of file system.cpp.
References env_vars.
store_hash()
void CBuild::store_hash (std::string toolchain_id)
Store new hashes to file.
Parameters
toolchain_id => std::string -> Id of toolchain
Definition at line 283 of file hash.cpp.
References CBUILD_BUILD_DIR, CBUILD_HASH_DIR, CBUILD_HASH_FILE, CBuild::vars::filelist, and CBuild::vars::headers.
Referenced by get_files().
system()
int CBuild::system (std::string cmd)
Call stdlib system() and print cmd to shell.
Parameters
cmd => std::string -> command
Returns
int -> Shell return code
Definition at line 47 of file system.cpp.
References BLUE, enabled, get_env_vars(), log, and print().
Referenced by CBuild::Toolchain::call(), CBuild::Toolchain::clear(), CBuild::Toolchain::compile(), CBuild::Toolchain::debug(), CBuild::Toolchain::load_project_deps(), rebuild(), CBuild::Toolchain::run(), and CBuild::MINGW_GXX::run().
system_piped()
std::string CBuild::system_piped (std::string cmd, unsigned int buffsize)
Execute command and return it's output.
Parameters
cmd => stt::string -> command
buffsize => unsigned int -> Size of output buffer, malloc and fread
Returns
std::string -> Program output
Definition at line 58 of file system.cpp.
References BLUE, enabled, CBuild::fs::FILE, get_env_vars(), log, and print().
Referenced by get_pkg_info().
task_handler()
ARG_TYPE CBuild::task_handler (lib::map< std::string, std::string > * args, char ** argv, int argc, int ptr, CBuild::RType * type)
Definition at line 189 of file cli_parser.cpp.
References exit(), lib::map< _K, _D >::get_ptr(), CBuild::Registry::GetTasksList(), GREEN, print(), print_full(), lib::map< _K, _D >::push_back_check(), RED, TASK, TASK_ARG, and CBuild::Registry::tasks.
Variable Documentation
arg
int CBuild::arg = 0
Definition at line 233 of file cli_parser.cpp.
Referenced by CBuild::Toolchain::add_compile_arg(), CBuild::Toolchain::add_link_arg(), CBuild::Registry::AddCompileArg(), CBuild::Registry::AddLinkArg(), arg_handler(), and CBuild::Toolchain::get_compile_args().
enabled
bool CBuild::enabled = true
Definition at line 34 of file system.cpp.
Referenced by disable_system(), system(), and system_piped().
env_vars
std::map<std::string, std::string> CBuild::env_vars
Definition at line 33 of file system.cpp.
Referenced by add_env_var(), change_env_var(), get_env_vars(), and remove_env_var().
log
std::vector<std::string> CBuild::log
Definition at line 32 of file system.cpp.
Referenced by CBuild::makefile_out::generate(), get_log(), system(), and system_piped().
none
bool CBuild::none = false
Definition at line 27 of file print.cpp.
Referenced by print(), print_full(), and print_none().
parg
int CBuild::parg = 0
Definition at line 234 of file cli_parser.cpp.
Referenced by arg_handler().
parsers_list
lib::map<std::string, handler> CBuild::parsers_list
Initial value:
= {
    {"-f", &force_handler},         {"-v", &out_handler},
    {"--no-cli-out", &out_handler}, {"-g", &generator_handler},
    {"-b", &build_handler},         {"-r", &build_handler},
    {"-br", &build_handler},        {"-d", &build_handler},
    {"-ld", &build_handler},        {"-c", &build_handler},
    {"-t", &task_handler},          {"-a", &arg_handler},
    {"-pa", &arg_handler},          {"--rebuild", &rebuild_handler}}
All handlers.
Definition at line 281 of file cli_parser.cpp.
Referenced by parse(), and register_parse_handler().
real_exit
bool CBuild::real_exit = true
Definition at line 33 of file cli_parser.cpp.
Referenced by exit().
verbose
bool CBuild::verbose = false
Definition at line 26 of file print.cpp.
Referenced by print_full(), and print_verbose().
version
int CBuild::version[] = {CBUILD_VERSION_MAJOR, CBUILD_VERSION_MINOR}
Definition at line 567 of file CBuild.cpp.
Referenced by get_version_array(), and CBuild::Toolchain::set_version_major().