CBuild: CBuild::Registry Namespace Reference
CBuild::Registry Namespace Reference
Functions
void init ()
Internal init.
void RegisterTask (CBuild::Task *task)
Register new task.
void CallTask (std::string name, std::vector< std::string > args)
Run tasks.
void RegisterTarget (CBuild::Toolchain *target)
Register new target for build.
CBuild::Toolchain * GetToolchain (std::string name, bool force=false)
Get the registered toolchain.
lib::map< std::string, CBuild::Toolchain * > GetTargets ()
Get list of all targets.
void RegisterKeyword (std::string key, CBuild::Task *func)
Register new keyord for parsing, ! Dangerous, owerwriting existing keywords can lead to undefined behaviours.
lib::map< std::string, std::string > GetKeywordsList ()
Get list of all user registered keywords.
void SetRebuildName (std::string _name)
Set the rebuilt CBuild executable name.
void AddLinkArg (std::string arg)
Add linker arg for CBuild rebuild.
void AddCompileArg (std::string arg)
Add compiler argument for CBuild rebuild.
void SetVersionHandler (void(*handler)())
Set handler to add output to --version
std::string GetRebuildArgs ()
Get the rebuild args for CBuild executable.
void ToolchainAll (bool force, std::string path, std::vector< std::string > *args)
Call and execute all toolchains.
CBuild::generator_base * GetGenerator (std::string id)
Get generator for specified id.
void RegisterGenerator (CBuild::generator_base *gen, std::string id)
Register generator for id.
std::vector< std::string > GetGeneratorsList ()
Get list of registered generators.
std::vector< std::string > GetToolchainsList ()
Get list of registered toolchains.
std::vector< std::string > GetTasksList ()
Get list of registered tasks.
void null_handler ()
Variables
void(* handler)() = Registry::null_handler
CBuild::Help help
CBuild::Init initw
CBuild::Version ver
CBuild::TaskList tasklist
CBuild::ToolchainList toolchainlist
CBuild::GeneratorList generatorlist
CBuild::CmdList cmdlist
CBuild::ccj_out ccjo
CBuild::makefile_out makefileo
lib::map< std::string, CBuild::Task * > tasks
lib::map< std::string, bool > task_executed
lib::map< std::string, CBuild::Toolchain * > targets
lib::map< std::string, bool > target_executed
lib::map< std::string, std::string > keywords
std::string name = "CBuild.run"
std::vector< std::string > cargs
std::vector< std::string > largs
lib::map< std::string, CBuild::generator_base * > generators
Function Documentation
AddCompileArg()
void CBuild::Registry::AddCompileArg (std::string arg)
Add compiler argument for CBuild rebuild.
Parameters
arg => std::string -> raw argument
Definition at line 281 of file register.cpp.
References CBuild::arg.
AddLinkArg()
void CBuild::Registry::AddLinkArg (std::string arg)
Add linker arg for CBuild rebuild.
Parameters
arg => std::string -> raw argument
Definition at line 277 of file register.cpp.
References CBuild::arg, and lib::map< _K, _D >::push_back().
CallTask()
void CBuild::Registry::CallTask (std::string name, std::vector< std::string > args)
Run tasks.
Parameters
name => std::string -> Name of task
args => std::vector<std::string> -> Arguments for task
Definition at line 194 of file register.cpp.
References name, CBuild::print(), and CBuild::RED.
Referenced by CBuild::Toolchain::call(), and CBuild::loop().
GetGenerator()
CBuild::generator_base * CBuild::Registry::GetGenerator (std::string id)
Get generator for specified id.
Parameters
id => std::string -> Generator id
Returns
CBuild::generator_base* -> Pointer to generator instance
Definition at line 328 of file register.cpp.
Referenced by CBuild::loop().
GetGeneratorsList()
std::vector< std::string > CBuild::Registry::GetGeneratorsList ()
Get list of registered generators.
Returns
std::vector<std::string> -> List of generators
Definition at line 344 of file register.cpp.
References generators.
Referenced by CBuild::GeneratorList::call(), and CBuild::generator_handler().
GetKeywordsList()
lib::map< std::string, std::string > CBuild::Registry::GetKeywordsList ()
Get list of all user registered keywords.
Returns
lib::map<std::string, std::string> where key - keyword, value - task id to call
Definition at line 268 of file register.cpp.
Referenced by CBuild::CmdList::call(), and CBuild::parse().
GetRebuildArgs()
std::string CBuild::Registry::GetRebuildArgs ()
Get the rebuild args for CBuild executable.
Returns
std::string -> formatted arguments
Definition at line 285 of file register.cpp.
Referenced by CBuild::rebuild().
GetTargets()
lib::map< std::string, CBuild::Toolchain * > CBuild::Registry::GetTargets ()
Get list of all targets.
Returns
lib::map<std::string, CBuild::Toolchain*>
Definition at line 253 of file register.cpp.
GetTasksList()
std::vector< std::string > CBuild::Registry::GetTasksList ()
Get list of registered tasks.
Returns
std::vector<std::string> -> List of tasks
Definition at line 358 of file register.cpp.
References tasks.
Referenced by CBuild::TaskList::call(), and CBuild::task_handler().
GetToolchain()
CBuild::Toolchain * CBuild::Registry::GetToolchain (std::string name, bool force = false)
Get the registered toolchain.
Parameters
name => std::string -> target id
force => bool -> default = false, if true does not look in list of executed toolchains
Returns
CBuild::Toolchain* -> pointer to toolchain or null if target with given id does not exists
Definition at line 229 of file register.cpp.
References name.
Referenced by CBuild::Toolchain::call(), CBuild::ccj_out::generate(), CBuild::loop(), CBuild::MINGW_GXX::post_link(), and CBuild::MINGW_GCC::post_link().
GetToolchainsList()
std::vector< std::string > CBuild::Registry::GetToolchainsList ()
Get list of registered toolchains.
Returns
std::vector<std::string> -> List of toolchains
Definition at line 351 of file register.cpp.
References targets.
Referenced by CBuild::build_handler(), and CBuild::ToolchainList::call().
init()
void CBuild::Registry::init ()
Internal init.
Definition at line 161 of file register.cpp.
References ccjo, cmdlist, generatorlist, help, initw, makefileo, tasklist, toolchainlist, and ver.
Referenced by CBuild::parse().
null_handler()
void CBuild::Registry::null_handler ()
Definition at line 40 of file register.cpp.
RegisterGenerator()
void CBuild::Registry::RegisterGenerator (CBuild::generator_base * gen, std::string id)
Register generator for id.
Parameters
gen => CBuild::generator_base* -> Generator instance
id => std::string -> Geneator id
Definition at line 335 of file register.cpp.
References CBuild::print_full(), and CBuild::RED.
RegisterKeyword()
void CBuild::Registry::RegisterKeyword (std::string key, CBuild::Task * func)
Register new keyord for parsing, ! Dangerous, owerwriting existing keywords can lead to undefined behaviours.
Parameters
key => std::string -> new keyword
func => Cbuild::Task -> task, associated with keyword
Definition at line 257 of file register.cpp.
References CBuild::print_full(), CBuild::RED, and CBuild::Task::self_name().
RegisterTarget()
void CBuild::Registry::RegisterTarget (CBuild::Toolchain * target)
Register new target for build.
Parameters
target => CBuild::Toolchain* -> Pointer to staticly allocated class that extends CBuild::Toolchain
Definition at line 215 of file register.cpp.
References CBuild::Toolchain::get_id(), CBuild::print_full(), and CBuild::RED.
RegisterTask()
void CBuild::Registry::RegisterTask (CBuild::Task * task)
Register new task.
Parameters
task => CBuild::Task* -> pointer to staticly allocated task
Definition at line 181 of file register.cpp.
References CBuild::print_full(), CBuild::RED, and CBuild::Task::self_name().
SetRebuildName()
void CBuild::Registry::SetRebuildName (std::string _name)
Set the rebuilt CBuild executable name.
Parameters
_name => std::string -> new CBuild user executable name
Definition at line 273 of file register.cpp.
SetVersionHandler()
void CBuild::Registry::SetVersionHandler (void(*)() handler)
Set handler to add output to --version
Parameters
handler => void (*)() -> Handler
Definition at line 365 of file register.cpp.
References handler.
ToolchainAll()
void CBuild::Registry::ToolchainAll (bool force, std::string path, std::vector< std::string > * args)
Call and execute all toolchains.
Parameters
force => bool -> Compilation type
path => std::string -> Base path
args => std::vector<std::string>* -> PArgs
Definition at line 305 of file register.cpp.
Referenced by CBuild::loop().
Variable Documentation
cargs
std::vector<std::string> CBuild::Registry::cargs
Definition at line 154 of file register.cpp.
ccjo
CBuild::ccj_out CBuild::Registry::ccjo
Definition at line 138 of file register.cpp.
Referenced by init().
cmdlist
CBuild::CmdList CBuild::Registry::cmdlist
Definition at line 136 of file register.cpp.
Referenced by init().
generatorlist
CBuild::GeneratorList CBuild::Registry::generatorlist
Definition at line 135 of file register.cpp.
Referenced by init().
generators
lib::map<std::string, CBuild::generator_base *> CBuild::Registry::generators
Definition at line 157 of file register.cpp.
Referenced by GetGeneratorsList().
handler
void(* CBuild::Registry::handler) () () = Registry::null_handler
Definition at line 42 of file register.cpp.
Referenced by CBuild::Version::call(), and SetVersionHandler().
help
CBuild::Help CBuild::Registry::help
Definition at line 130 of file register.cpp.
Referenced by init().
initw
CBuild::Init CBuild::Registry::initw
Definition at line 131 of file register.cpp.
Referenced by init().
keywords
lib::map<std::string, std::string> CBuild::Registry::keywords
Definition at line 150 of file register.cpp.
largs
std::vector<std::string> CBuild::Registry::largs
Definition at line 155 of file register.cpp.
makefileo
CBuild::makefile_out CBuild::Registry::makefileo
Definition at line 139 of file register.cpp.
Referenced by init().
name
std::string CBuild::Registry::name = "CBuild.run"
Definition at line 152 of file register.cpp.
Referenced by CallTask(), and GetToolchain().
target_executed
lib::map<std::string, bool> CBuild::Registry::target_executed
Definition at line 148 of file register.cpp.
targets
lib::map<std::string, CBuild::Toolchain *> CBuild::Registry::targets
Definition at line 146 of file register.cpp.
Referenced by GetToolchainsList().
task_executed
lib::map<std::string, bool> CBuild::Registry::task_executed
Definition at line 144 of file register.cpp.
tasklist
CBuild::TaskList CBuild::Registry::tasklist
Definition at line 133 of file register.cpp.
Referenced by init().
tasks
lib::map<std::string, CBuild::Task *> CBuild::Registry::tasks
Definition at line 142 of file register.cpp.
Referenced by GetTasksList().
toolchainlist
CBuild::ToolchainList CBuild::Registry::toolchainlist
Definition at line 134 of file register.cpp.
Referenced by init().
ver
CBuild::Version CBuild::Registry::ver
Definition at line 132 of file register.cpp.
Referenced by init().